### ISSUE TITLE
Error in XML result writer

### ISSUE THREAD

**Issue by tkurz** [TSO-Openup/FlintSparqlEditor#1]
xml result writer mixes results. Given the query

SELECT ?o ?p ?s WHERE {?s ?p ?o}

a result xml may look like:
...

```
<head>
        <variable name='o'/>
        <variable name='p'/>
        <variable name='s'/>
    </head>
    <results>
        <result>
            <binding name='s'>
                <uri>uri1</uri>
            </binding>
            <binding name='p'>
                <uri>uri2</uri>
            </binding>
            <binding name='o'>
                <literal>Hello</literal>
            </binding>
```

...
The xml result writer does not care about binding names in the result so e.g. the literal 'Hello' (which has binding 'o') is written in the 's' column.

**Comment by sncresswell** [comment]
Thanks for reporting. This is now fixed (v1.0.3).
