### ISSUE TITLE
With BigData(R) server : "The request was not sent. You may be offline."

### ISSUE THREAD

**Issue by jmvanel** [TSO-Openup/FlintSparqlEditor#5]
With BigData(R) I get the message:
"The request was not sent. You may be offline."

I'm using latest BigData(R) 1.4.0 :
http://bigdata.com/download
with this endpoint URL :
http://localhost:9999/bigdata/sparql
or
http:/192.168.1.80:9999/bigdata/sparql

Although this same endpoint URI works fine with EulerGUI ( using Jena ARQ client library ) ,
and with curl:
curl -i -d  'query=SELECT \* WHERE { ?s ?p ?o } LIMIT 3' http://localhost:9999/bigdata/sparql

Also, FlintSparqlEditor works fine with a local installation of Jena Fuseki,
and with
http://dbpedia.org/sparql

**Comment by jmvanel** [comment]
I investigated the actual HTTP sent with Chomium dev tools.
It seems that the Content-Type : application/x-www-form-urlencoded is a problem with the BigData(R)  SPARQL server.

This is confirmed by sending the query by curl :
curl -F 'query=SELECT \* WHERE { ?s ?p ?o } LIMIT 3' http://localhost:9999/bigdata/sparql
Content-Type not recognized as RDF: multipart/form-data; boundary=------------------------8d4cb49c4db3c731%                                           

whereas plain HTTP POST data works : 
curl -i -d  'query=SELECT \* WHERE { ?s ?p ?o } LIMIT 3' http://localhost:9999/bigdata/sparql | head
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1204    0  1163  100    41  13022    459 --:--:-- --:--:-- --:--:-- 13067
HTTP/1.1 200 OK
Content-Type: application/sparql-results+xml
Transfer-Encoding: chunked
Server: Jetty(9.1.4.v20140401)

<?xml version='1.0' encoding='UTF-8'?>
<sparql xmlns='http://www.w3.org/2005/sparql-results#'>
    <head>
        <variable name='s'/>
        <variable name='p'/>
...

The actual HTTP sent by Flint , seen with Chomium dev tools :

Request URL:http://localhost:9999/bigdata/sparql
Request Headers
Provisional headers are shown
Accept:text/plain
Content-Type:application/x-www-form-urlencoded
Origin:null
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/37.0.2062.120 Chrome/37.0.2062.120 Safari/537.36
X-DevTools-Emulate-Network-Conditions-Client-Id:D633FCF2-6DEA-DF00-4B1F-693F80DE0CF1
Form Dataview sourceview URL encoded
query:PREFIX rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
PREFIX rdfs: http://www.w3.org/2000/01/rdf-schema#

SELECT \* WHERE {
   ?s ?p ?o
}
LIMIT 10

With firefox, this is much the same.

**Comment by jmvanel** [comment]
For one more comparison, here is what the BigData(R) web console sends.
So the problem with Flint may be with Accept:text/plain , and definitely not with:
Content-Type:application/x-www-form-urlencoded
that is present here:

Remote Address:[::1]:9999
Request URL:http://localhost:9999/bigdata/namespace/kb/sparql
Request Method:POST
Status Code:200 OK
Request Headersview source
Accept:application/sparql-results+json
Accept-Encoding:gzip,deflate
Accept-Language:fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4
Connection:keep-alive
Content-Length:237
Content-Type:application/x-www-form-urlencoded; charset=UTF-8
Cookie:workspacePreferencesId=WSP1; JSESSIONID=y92sipwuu3l31xpgbk00ii9c3
Host:localhost:9999
Origin:http://localhost:9999
Referer:http://localhost:9999/bigdata/
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/37.0.2062.120 Chrome/37.0.2062.120 Safari/537.36
X-Requested-With:XMLHttpRequest
Form Dataview sourceview URL encoded
query:PREFIX rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
PREFIX rdfs: http://www.w3.org/2000/01/rdf-schema#

SELECT \* WHERE {
   ?s ?p ?o
}
LIMIT 10
Response Headersview source
Content-Type:application/sparql-results+json
Server:Jetty(9.1.4.v20140401)
Transfer-Encoding:chunked

**Comment by sncresswell** [comment]
Hi Jean-Marc,

Depending on how you are accessing the Flint page in the browser, this is likely to be related to the single-origin policy enforced by browsers for security.  

The default behaviour is to disallow AJAX requests to a service that is not on the same site as the page running the script.  Even if you load Flint from local files, and access a SPARQL endpoint on localhost, the single-origin policy will stop this from working.

The reason that it works with Fuseki is that Fuseki includes a CORS header with the response:

```
Access-Control-Allow-Origin: *
```

... which indicates that access to the service should be allowed from any origin.

It appears that, by default, BigData does not include this response header, but I think the answer is here:
http://sourceforge.net/p/bigdata/discussion/676946/thread/bf76fb62/?limit=25

Stephen Cresswell

**Comment by jmvanel** [comment]
Thanks Stephen

Indeed copying FlintSparqlEditor at the right place within BigData source works :

```
cd ~/src/BIGDATA_RELEASE_1_4_0/bigdata-war/src/html/
cp -r ~/src/FlintSparqlEditor .
```

and then rebuiling and restarting BigData, and accessing to :
[http://localhost:9999/bigdata/html/FlintSparqlEditor/sparql-editor.html](http://localhost:9999/bigdata/html/FlintSparqlEditor/sparql-editor.html)
